// Generated by `wit-bindgen` 0.9.0. DO NOT EDIT!
#include "state.h"


__attribute__((__import_module__("dapr:state/state-interface"), __import_name__("get")))
void __wasm_import_dapr_state_state_interface_get(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("dapr:state/state-interface"), __import_name__("set")))
void __wasm_import_dapr_state_state_interface_set(int32_t, int32_t);

__attribute__((__import_module__("dapr:state/state-interface"), __import_name__("delete")))
void __wasm_import_dapr_state_state_interface_delete(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void dapr_state_state_types_error_free(dapr_state_state_types_error_t *ptr) {
  state_string_free(ptr);
}

void dapr_state_state_types_store_name_free(dapr_state_state_types_store_name_t *ptr) {
  state_string_free(ptr);
}

void dapr_state_state_types_key_free(dapr_state_state_types_key_t *ptr) {
  state_string_free(ptr);
}

void state_tuple2_string_string_free(state_tuple2_string_string_t *ptr) {
  state_string_free(&ptr->f0);
  state_string_free(&ptr->f1);
}

void dapr_state_state_types_metadata_free(dapr_state_state_types_metadata_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    state_tuple2_string_string_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void state_option_dapr_state_state_types_metadata_free(state_option_dapr_state_state_types_metadata_t *ptr) {
  if (ptr->is_some) {
    dapr_state_state_types_metadata_free(&ptr->val);
  }
}

void dapr_state_state_types_get_request_free(dapr_state_state_types_get_request_t *ptr) {
  dapr_state_state_types_key_free(&ptr->key);
  state_option_dapr_state_state_types_metadata_free(&ptr->metadata);
}

void dapr_state_state_types_data_free(dapr_state_state_types_data_t *ptr) {
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void dapr_state_state_types_etag_free(dapr_state_state_types_etag_t *ptr) {
  if (ptr->is_some) {
    state_string_free(&ptr->val);
  }
}

void dapr_state_state_types_content_type_free(dapr_state_state_types_content_type_t *ptr) {
  if (ptr->is_some) {
    state_string_free(&ptr->val);
  }
}

void dapr_state_state_types_get_response_free(dapr_state_state_types_get_response_t *ptr) {
  dapr_state_state_types_data_free(&ptr->data);
  dapr_state_state_types_etag_free(&ptr->etag);
  state_option_dapr_state_state_types_metadata_free(&ptr->metadata);
  dapr_state_state_types_content_type_free(&ptr->content_type);
}

void dapr_state_state_types_set_request_free(dapr_state_state_types_set_request_t *ptr) {
  dapr_state_state_types_key_free(&ptr->key);
  dapr_state_state_types_data_free(&ptr->value);
  dapr_state_state_types_etag_free(&ptr->etag);
  state_option_dapr_state_state_types_metadata_free(&ptr->metadata);
  dapr_state_state_types_content_type_free(&ptr->content_type);
}

void dapr_state_state_types_delete_request_free(dapr_state_state_types_delete_request_t *ptr) {
  dapr_state_state_types_key_free(&ptr->key);
  dapr_state_state_types_etag_free(&ptr->etag);
  state_option_dapr_state_state_types_metadata_free(&ptr->metadata);
}

void dapr_state_state_interface_store_name_free(dapr_state_state_interface_store_name_t *ptr) {
  dapr_state_state_types_store_name_free(ptr);
}

void dapr_state_state_interface_get_request_free(dapr_state_state_interface_get_request_t *ptr) {
  dapr_state_state_types_get_request_free(ptr);
}

void dapr_state_state_interface_get_response_free(dapr_state_state_interface_get_response_t *ptr) {
  dapr_state_state_types_get_response_free(ptr);
}

void dapr_state_state_interface_set_request_free(dapr_state_state_interface_set_request_t *ptr) {
  dapr_state_state_types_set_request_free(ptr);
}

void dapr_state_state_interface_delete_request_free(dapr_state_state_interface_delete_request_t *ptr) {
  dapr_state_state_types_delete_request_free(ptr);
}

void dapr_state_state_interface_error_free(dapr_state_state_interface_error_t *ptr) {
  dapr_state_state_types_error_free(ptr);
}

void state_result_dapr_state_state_interface_get_response_dapr_state_state_interface_error_free(state_result_dapr_state_state_interface_get_response_dapr_state_state_interface_error_t *ptr) {
  if (!ptr->is_err) {
    dapr_state_state_interface_get_response_free(&ptr->val.ok);
  } else {
    dapr_state_state_interface_error_free(&ptr->val.err);
  }
}

void state_result_u32_dapr_state_state_interface_error_free(state_result_u32_dapr_state_state_interface_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    dapr_state_state_interface_error_free(&ptr->val.err);
  }
}

void state_string_set(state_string_t *ret, const char*s) {
  ret->ptr = (char*) s;
  ret->len = strlen(s);
}

void state_string_dup(state_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void state_string_free(state_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void dapr_state_state_interface_get(dapr_state_state_interface_store_name_t *name, dapr_state_state_interface_get_request_t *req, state_result_dapr_state_state_interface_get_response_dapr_state_state_interface_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[48];
  int32_t option;
  int32_t option1;
  int32_t option2;
  if (((*req).metadata).is_some) {
    const dapr_state_state_types_metadata_t *payload0 = &((*req).metadata).val;
    option = 1;
    option1 = (int32_t) (*payload0).ptr;
    option2 = (int32_t) (*payload0).len;
  } else {
    option = 0;
    option1 = 0;
    option2 = 0;
  }
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_dapr_state_state_interface_get((int32_t) (*name).ptr, (int32_t) (*name).len, (int32_t) ((*req).key).ptr, (int32_t) ((*req).key).len, option, option1, option2, (int32_t) ((*req).options).consistency, ptr);
  state_result_dapr_state_state_interface_get_response_dapr_state_state_interface_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      dapr_state_state_types_etag_t option3;
      switch ((int32_t) (*((uint8_t*) (ptr + 12)))) {
        case 0: {
          option3.is_some = false;
          break;
        }
        case 1: {
          option3.is_some = true;
          option3.val = (state_string_t) { (char*)(*((int32_t*) (ptr + 16))), (size_t)(*((int32_t*) (ptr + 20))) };
          break;
        }
      }
      state_option_dapr_state_state_types_metadata_t option4;
      switch ((int32_t) (*((uint8_t*) (ptr + 24)))) {
        case 0: {
          option4.is_some = false;
          break;
        }
        case 1: {
          option4.is_some = true;
          option4.val = (dapr_state_state_types_metadata_t) { (state_tuple2_string_string_t*)(*((int32_t*) (ptr + 28))), (size_t)(*((int32_t*) (ptr + 32))) };
          break;
        }
      }
      dapr_state_state_types_content_type_t option5;
      switch ((int32_t) (*((uint8_t*) (ptr + 36)))) {
        case 0: {
          option5.is_some = false;
          break;
        }
        case 1: {
          option5.is_some = true;
          option5.val = (state_string_t) { (char*)(*((int32_t*) (ptr + 40))), (size_t)(*((int32_t*) (ptr + 44))) };
          break;
        }
      }
      
      result.val.ok = (dapr_state_state_types_get_response_t) {
        (dapr_state_state_types_data_t) { (uint8_t*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) },
        option3,
        option4,
        option5,
      };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (state_string_t) { (char*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
  }
  *ret = result;
}

void dapr_state_state_interface_set(dapr_state_state_interface_store_name_t *name, dapr_state_state_interface_set_request_t *req, state_result_u32_dapr_state_state_interface_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[64];
  int32_t ptr = (int32_t) &ret_area;
  *((int32_t*)(ptr + 4)) = (int32_t) (*name).len;
  *((int32_t*)(ptr + 0)) = (int32_t) (*name).ptr;
  *((int32_t*)(ptr + 12)) = (int32_t) ((*req).key).len;
  *((int32_t*)(ptr + 8)) = (int32_t) ((*req).key).ptr;
  *((int32_t*)(ptr + 20)) = (int32_t) ((*req).value).len;
  *((int32_t*)(ptr + 16)) = (int32_t) ((*req).value).ptr;
  if (((*req).etag).is_some) {
    const state_string_t *payload0 = &((*req).etag).val;
    *((int8_t*)(ptr + 24)) = 1;
    *((int32_t*)(ptr + 32)) = (int32_t) (*payload0).len;
    *((int32_t*)(ptr + 28)) = (int32_t) (*payload0).ptr;
  } else {
    *((int8_t*)(ptr + 24)) = 0;
  }
  if (((*req).metadata).is_some) {
    const dapr_state_state_types_metadata_t *payload2 = &((*req).metadata).val;
    *((int8_t*)(ptr + 36)) = 1;
    *((int32_t*)(ptr + 44)) = (int32_t) (*payload2).len;
    *((int32_t*)(ptr + 40)) = (int32_t) (*payload2).ptr;
  } else {
    *((int8_t*)(ptr + 36)) = 0;
  }
  *((int8_t*)(ptr + 48)) = (int32_t) ((*req).options).concurrency;
  *((int8_t*)(ptr + 49)) = (int32_t) ((*req).options).consistency;
  if (((*req).content_type).is_some) {
    const state_string_t *payload4 = &((*req).content_type).val;
    *((int8_t*)(ptr + 52)) = 1;
    *((int32_t*)(ptr + 60)) = (int32_t) (*payload4).len;
    *((int32_t*)(ptr + 56)) = (int32_t) (*payload4).ptr;
  } else {
    *((int8_t*)(ptr + 52)) = 0;
  }
  int32_t ptr5 = (int32_t) &ret_area;
  __wasm_import_dapr_state_state_interface_set(ptr, ptr5);
  state_result_u32_dapr_state_state_interface_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr5 + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint32_t) (*((int32_t*) (ptr5 + 4)));
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (state_string_t) { (char*)(*((int32_t*) (ptr5 + 4))), (size_t)(*((int32_t*) (ptr5 + 8))) };
      break;
    }
  }
  *ret = result;
}

void dapr_state_state_interface_delete(dapr_state_state_interface_store_name_t *name, dapr_state_state_interface_delete_request_t *req, state_result_u32_dapr_state_state_interface_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t option;
  int32_t option1;
  int32_t option2;
  if (((*req).etag).is_some) {
    const state_string_t *payload0 = &((*req).etag).val;
    option = 1;
    option1 = (int32_t) (*payload0).ptr;
    option2 = (int32_t) (*payload0).len;
  } else {
    option = 0;
    option1 = 0;
    option2 = 0;
  }
  int32_t option5;
  int32_t option6;
  int32_t option7;
  if (((*req).metadata).is_some) {
    const dapr_state_state_types_metadata_t *payload4 = &((*req).metadata).val;
    option5 = 1;
    option6 = (int32_t) (*payload4).ptr;
    option7 = (int32_t) (*payload4).len;
  } else {
    option5 = 0;
    option6 = 0;
    option7 = 0;
  }
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_dapr_state_state_interface_delete((int32_t) (*name).ptr, (int32_t) (*name).len, (int32_t) ((*req).key).ptr, (int32_t) ((*req).key).len, option, option1, option2, option5, option6, option7, (int32_t) ((*req).options).concurrency, (int32_t) ((*req).options).consistency, ptr);
  state_result_u32_dapr_state_state_interface_error_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint32_t) (*((int32_t*) (ptr + 4)));
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (state_string_t) { (char*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
  }
  *ret = result;
}

extern void __component_type_object_force_link_state(void);
void __component_type_object_force_link_state_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_state();
}
