// Generated by `wit-bindgen` 0.9.0. DO NOT EDIT!
#include "state.h"

__attribute__((__weak__, __export_name__("cabi_post_dapr:state/state-interface#get")))
void __wasm_export_exports_dapr_state_state_interface_get_post_return(int32_t arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      int32_t ptr = *((int32_t*) (arg0 + 4));
      int32_t len = *((int32_t*) (arg0 + 8));
      for (int32_t i = 0; i < len; i++) {
        int32_t base = ptr + i * 1;
        (void) base;
      }
      if (len > 0) {
        free((void*) (ptr));
      }
      switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 12)))) {
        case 0: {
          break;
        }
        case 1: {
          if ((*((int32_t*) (arg0 + 20))) > 0) {
            free((void*) (*((int32_t*) (arg0 + 16))));
          }
          break;
        }
      }
      switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 24)))) {
        case 0: {
          break;
        }
        case 1: {
          int32_t ptr0 = *((int32_t*) (arg0 + 28));
          int32_t len1 = *((int32_t*) (arg0 + 32));
          for (int32_t i2 = 0; i2 < len1; i2++) {
            int32_t base = ptr0 + i2 * 16;
            (void) base;
            if ((*((int32_t*) (base + 4))) > 0) {
              free((void*) (*((int32_t*) (base + 0))));
            }
            if ((*((int32_t*) (base + 12))) > 0) {
              free((void*) (*((int32_t*) (base + 8))));
            }
          }
          if (len1 > 0) {
            free((void*) (ptr0));
          }
          break;
        }
      }
      switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 36)))) {
        case 0: {
          break;
        }
        case 1: {
          if ((*((int32_t*) (arg0 + 44))) > 0) {
            free((void*) (*((int32_t*) (arg0 + 40))));
          }
          break;
        }
      }
      break;
    }
    case 1: {
      if ((*((int32_t*) (arg0 + 8))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 4))));
      }
      break;
    }
  }
}
__attribute__((__weak__, __export_name__("cabi_post_dapr:state/state-interface#set")))
void __wasm_export_exports_dapr_state_state_interface_set_post_return(int32_t arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((int32_t*) (arg0 + 8))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 4))));
      }
      break;
    }
  }
}
__attribute__((__weak__, __export_name__("cabi_post_dapr:state/state-interface#delete")))
void __wasm_export_exports_dapr_state_state_interface_delete_post_return(int32_t arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((int32_t*) (arg0 + 8))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 4))));
      }
      break;
    }
  }
}

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void dapr_state_state_types_error_free(dapr_state_state_types_error_t *ptr) {
  state_string_free(ptr);
}

void dapr_state_state_types_key_free(dapr_state_state_types_key_t *ptr) {
  state_string_free(ptr);
}

void state_tuple2_string_string_free(state_tuple2_string_string_t *ptr) {
  state_string_free(&ptr->f0);
  state_string_free(&ptr->f1);
}

void dapr_state_state_types_metadata_free(dapr_state_state_types_metadata_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    state_tuple2_string_string_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void dapr_state_state_types_consistency_free(dapr_state_state_types_consistency_t *ptr) {
  state_string_free(ptr);
}

void dapr_state_state_types_get_state_options_free(dapr_state_state_types_get_state_options_t *ptr) {
  dapr_state_state_types_consistency_free(&ptr->consistency);
}

void state_option_dapr_state_state_types_metadata_free(state_option_dapr_state_state_types_metadata_t *ptr) {
  if (ptr->is_some) {
    dapr_state_state_types_metadata_free(&ptr->val);
  }
}

void state_option_dapr_state_state_types_get_state_options_free(state_option_dapr_state_state_types_get_state_options_t *ptr) {
  if (ptr->is_some) {
    dapr_state_state_types_get_state_options_free(&ptr->val);
  }
}

void dapr_state_state_types_get_request_free(dapr_state_state_types_get_request_t *ptr) {
  dapr_state_state_types_key_free(&ptr->key);
  state_option_dapr_state_state_types_metadata_free(&ptr->metadata);
  state_option_dapr_state_state_types_get_state_options_free(&ptr->options);
}

void dapr_state_state_types_data_free(dapr_state_state_types_data_t *ptr) {
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void dapr_state_state_types_etag_free(dapr_state_state_types_etag_t *ptr) {
  if (ptr->is_some) {
    state_string_free(&ptr->val);
  }
}

void dapr_state_state_types_content_type_free(dapr_state_state_types_content_type_t *ptr) {
  if (ptr->is_some) {
    state_string_free(&ptr->val);
  }
}

void dapr_state_state_types_get_response_free(dapr_state_state_types_get_response_t *ptr) {
  dapr_state_state_types_data_free(&ptr->data);
  dapr_state_state_types_etag_free(&ptr->etag);
  state_option_dapr_state_state_types_metadata_free(&ptr->metadata);
  dapr_state_state_types_content_type_free(&ptr->content_type);
}

void dapr_state_state_types_set_state_options_free(dapr_state_state_types_set_state_options_t *ptr) {
  state_string_free(&ptr->concurrency);
  dapr_state_state_types_consistency_free(&ptr->consistency);
}

void dapr_state_state_types_set_request_free(dapr_state_state_types_set_request_t *ptr) {
  dapr_state_state_types_key_free(&ptr->key);
  dapr_state_state_types_data_free(&ptr->value);
  dapr_state_state_types_etag_free(&ptr->etag);
  state_option_dapr_state_state_types_metadata_free(&ptr->metadata);
  dapr_state_state_types_set_state_options_free(&ptr->options);
  dapr_state_state_types_content_type_free(&ptr->content_type);
}

void dapr_state_state_types_delete_request_free(dapr_state_state_types_delete_request_t *ptr) {
  dapr_state_state_types_key_free(&ptr->key);
  dapr_state_state_types_etag_free(&ptr->etag);
  state_option_dapr_state_state_types_metadata_free(&ptr->metadata);
  dapr_state_state_types_set_state_options_free(&ptr->options);
}

void dapr_state_state_interface_get_request_free(dapr_state_state_interface_get_request_t *ptr) {
  dapr_state_state_types_get_request_free(ptr);
}

void dapr_state_state_interface_get_response_free(dapr_state_state_interface_get_response_t *ptr) {
  dapr_state_state_types_get_response_free(ptr);
}

void dapr_state_state_interface_set_request_free(dapr_state_state_interface_set_request_t *ptr) {
  dapr_state_state_types_set_request_free(ptr);
}

void dapr_state_state_interface_delete_request_free(dapr_state_state_interface_delete_request_t *ptr) {
  dapr_state_state_types_delete_request_free(ptr);
}

void dapr_state_state_interface_error_free(dapr_state_state_interface_error_t *ptr) {
  dapr_state_state_types_error_free(ptr);
}

void state_result_dapr_state_state_interface_get_response_dapr_state_state_interface_error_free(state_result_dapr_state_state_interface_get_response_dapr_state_state_interface_error_t *ptr) {
  if (!ptr->is_err) {
    dapr_state_state_interface_get_response_free(&ptr->val.ok);
  } else {
    dapr_state_state_interface_error_free(&ptr->val.err);
  }
}

void state_result_u32_dapr_state_state_interface_error_free(state_result_u32_dapr_state_state_interface_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    dapr_state_state_interface_error_free(&ptr->val.err);
  }
}

void state_string_set(state_string_t *ret, const char*s) {
  ret->ptr = (char*) s;
  ret->len = strlen(s);
}

void state_string_dup(state_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void state_string_free(state_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(4)))
static uint8_t RET_AREA[48];

__attribute__((__export_name__("dapr:state/state-interface#get")))
int32_t __wasm_export_exports_dapr_state_state_interface_get(int32_t arg, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, int32_t arg4, int32_t arg5, int32_t arg6) {
  state_option_dapr_state_state_types_metadata_t option;
  switch (arg1) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (dapr_state_state_types_metadata_t) { (state_tuple2_string_string_t*)(arg2), (size_t)(arg3) };
      break;
    }
  }
  state_option_dapr_state_state_types_get_state_options_t option7;
  switch (arg4) {
    case 0: {
      option7.is_some = false;
      break;
    }
    case 1: {
      option7.is_some = true;
      option7.val = (dapr_state_state_types_get_state_options_t) {
        (state_string_t) { (char*)(arg5), (size_t)(arg6) },
      };
      break;
    }
  }
  dapr_state_state_interface_get_request_t arg8 = (dapr_state_state_types_get_request_t) {
    (state_string_t) { (char*)(arg), (size_t)(arg0) },
    option,
    option7,
  };
  state_result_dapr_state_state_interface_get_response_dapr_state_state_interface_error_t ret;
  exports_dapr_state_state_interface_get(&arg8, &ret);
  int32_t ptr = (int32_t) &RET_AREA;
  if ((ret).is_err) {
    const dapr_state_state_interface_error_t *payload15 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((int32_t*)(ptr + 8)) = (int32_t) (*payload15).len;
    *((int32_t*)(ptr + 4)) = (int32_t) (*payload15).ptr;
  } else {
    const dapr_state_state_interface_get_response_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((int32_t*)(ptr + 8)) = (int32_t) ((*payload).data).len;
    *((int32_t*)(ptr + 4)) = (int32_t) ((*payload).data).ptr;
    if (((*payload).etag).is_some) {
      const state_string_t *payload10 = &((*payload).etag).val;
      *((int8_t*)(ptr + 12)) = 1;
      *((int32_t*)(ptr + 20)) = (int32_t) (*payload10).len;
      *((int32_t*)(ptr + 16)) = (int32_t) (*payload10).ptr;
    } else {
      *((int8_t*)(ptr + 12)) = 0;
    }
    if (((*payload).metadata).is_some) {
      const dapr_state_state_types_metadata_t *payload12 = &((*payload).metadata).val;
      *((int8_t*)(ptr + 24)) = 1;
      *((int32_t*)(ptr + 32)) = (int32_t) (*payload12).len;
      *((int32_t*)(ptr + 28)) = (int32_t) (*payload12).ptr;
    } else {
      *((int8_t*)(ptr + 24)) = 0;
    }
    if (((*payload).content_type).is_some) {
      const state_string_t *payload14 = &((*payload).content_type).val;
      *((int8_t*)(ptr + 36)) = 1;
      *((int32_t*)(ptr + 44)) = (int32_t) (*payload14).len;
      *((int32_t*)(ptr + 40)) = (int32_t) (*payload14).ptr;
    } else {
      *((int8_t*)(ptr + 36)) = 0;
    }
  }
  return ptr;
}

__attribute__((__export_name__("dapr:state/state-interface#set")))
int32_t __wasm_export_exports_dapr_state_state_interface_set(int32_t arg) {
  dapr_state_state_types_etag_t option;
  switch ((int32_t) (*((uint8_t*) (arg + 16)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (state_string_t) { (char*)(*((int32_t*) (arg + 20))), (size_t)(*((int32_t*) (arg + 24))) };
      break;
    }
  }
  state_option_dapr_state_state_types_metadata_t option0;
  switch ((int32_t) (*((uint8_t*) (arg + 28)))) {
    case 0: {
      option0.is_some = false;
      break;
    }
    case 1: {
      option0.is_some = true;
      option0.val = (dapr_state_state_types_metadata_t) { (state_tuple2_string_string_t*)(*((int32_t*) (arg + 32))), (size_t)(*((int32_t*) (arg + 36))) };
      break;
    }
  }
  dapr_state_state_types_content_type_t option1;
  switch ((int32_t) (*((uint8_t*) (arg + 56)))) {
    case 0: {
      option1.is_some = false;
      break;
    }
    case 1: {
      option1.is_some = true;
      option1.val = (state_string_t) { (char*)(*((int32_t*) (arg + 60))), (size_t)(*((int32_t*) (arg + 64))) };
      break;
    }
  }
  dapr_state_state_interface_set_request_t arg2 = (dapr_state_state_types_set_request_t) {
    (state_string_t) { (char*)(*((int32_t*) (arg + 0))), (size_t)(*((int32_t*) (arg + 4))) },
    (dapr_state_state_types_data_t) { (uint8_t*)(*((int32_t*) (arg + 8))), (size_t)(*((int32_t*) (arg + 12))) },
    option,
    option0,
    (dapr_state_state_types_set_state_options_t) {
      (state_string_t) { (char*)(*((int32_t*) (arg + 40))), (size_t)(*((int32_t*) (arg + 44))) },
      (state_string_t) { (char*)(*((int32_t*) (arg + 48))), (size_t)(*((int32_t*) (arg + 52))) },
    },
    option1,
  };
  state_result_u32_dapr_state_state_interface_error_t ret;
  exports_dapr_state_state_interface_set(&arg2, &ret);
  free((void*) (arg));
  int32_t ptr = (int32_t) &RET_AREA;
  if ((ret).is_err) {
    const dapr_state_state_interface_error_t *payload3 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((int32_t*)(ptr + 8)) = (int32_t) (*payload3).len;
    *((int32_t*)(ptr + 4)) = (int32_t) (*payload3).ptr;
  } else {
    const uint32_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((int32_t*)(ptr + 4)) = (int32_t) (*payload);
  }
  return ptr;
}

__attribute__((__export_name__("dapr:state/state-interface#delete")))
int32_t __wasm_export_exports_dapr_state_state_interface_delete(int32_t arg, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, int32_t arg4, int32_t arg5, int32_t arg6, int32_t arg7, int32_t arg8, int32_t arg9, int32_t arg10) {
  dapr_state_state_types_etag_t option;
  switch (arg1) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (state_string_t) { (char*)(arg2), (size_t)(arg3) };
      break;
    }
  }
  state_option_dapr_state_state_types_metadata_t option11;
  switch (arg4) {
    case 0: {
      option11.is_some = false;
      break;
    }
    case 1: {
      option11.is_some = true;
      option11.val = (dapr_state_state_types_metadata_t) { (state_tuple2_string_string_t*)(arg5), (size_t)(arg6) };
      break;
    }
  }
  dapr_state_state_interface_delete_request_t arg12 = (dapr_state_state_types_delete_request_t) {
    (state_string_t) { (char*)(arg), (size_t)(arg0) },
    option,
    option11,
    (dapr_state_state_types_set_state_options_t) {
      (state_string_t) { (char*)(arg7), (size_t)(arg8) },
      (state_string_t) { (char*)(arg9), (size_t)(arg10) },
    },
  };
  state_result_u32_dapr_state_state_interface_error_t ret;
  exports_dapr_state_state_interface_delete(&arg12, &ret);
  int32_t ptr = (int32_t) &RET_AREA;
  if ((ret).is_err) {
    const dapr_state_state_interface_error_t *payload13 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((int32_t*)(ptr + 8)) = (int32_t) (*payload13).len;
    *((int32_t*)(ptr + 4)) = (int32_t) (*payload13).ptr;
  } else {
    const uint32_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((int32_t*)(ptr + 4)) = (int32_t) (*payload);
  }
  return ptr;
}

extern void __component_type_object_force_link_state(void);
void __component_type_object_force_link_state_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_state();
}
