package dapr:state

world state {
  export state-interface
}

interface state-interface {
  use state-types.{get-request,get-response,set-request,delete-request,error}

  get: func(req: get-request) -> result<get-response,error>
  set: func(req: set-request) -> result<u32,error>
  delete: func(req: delete-request) -> result<u32,error>
}